spring.application.name=dimaBeauty
spring.datasource.url=jdbc:mysql://localhost:3306/dimabeauty
spring.datasource.username=root
spring.datasource.password=99250602
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8088